SELECT STM.PLANTCODE
     , STM.MATLOTNO
	 , STM.ITEMCODE
	 , STM.STOCKQTY
  FROM TB_StockMM STM LEFT JOIN TB_ItemMaster ITM
                             ON STM.PLANTCODE = ITM.PLANTCODE
							AND STM.ITEMCODE  = ITM.ITEMCODE
 WHERE ITM.INSPFLAG = 'I'
;


SELECT GETDATE();