DECLARE @I INT =0, @STOPCODE VARCHAR(10) = '', @STOPNAME VARCHAR(10) = 'ÀçÇõ'
WHILE @I < 100
BEGIN
	IF @I <10
	BEGIN
		SET @STOPCODE = 'F0' + LTRIM(STR(@I))
	END;
	IF @I >= 10
	BEGIN
		SET @STOPCODE = 'F' + LTRIM(STR(@I))
	END;
	SET @I += 1
	INSERT INTO TB_StopListMaster (PLANTCODE, STOPCODE, STOPNAME, REMARK, USEFLAG, MAKER, MAKEDATE)
	VALUES ('1000', @STOPCODE, @STOPNAME, 'ÃÝºñ»ó~~~', 'Y', 'Á¨Áö', GETDATE());
END
/*
WHILE @I < 100
BEGIN
	SET @STOPCODE = 'F' + STR(@I)
	SET @I += 1
	INSERT INTO TB_StopListMaster (PLANTCODE, STOPCODE, STOPNAME, REMARK, USEFLAG, MAKER, MAKEDATE)
	VALUES ('1000', @STOPCODE, @STOPNAME, 'ÃÝºñ»ó~~~', 'Y', 'Á¨Áö', GETDATE());
END
*/

SELECT *
--DELETE
  FROM TB_StopListMaster
 WHERE STOPCODE LIKE '%F%'
;